### ISSUE TITLE
Update names when the date is changed

### ISSUE THREAD

**Issue by danchris** [danchris/eortologio-gnome-shell-extension#6]
Hi,

Until now the names that are showed in the panel are calculated according to the date that the extension is enabled. However, this is not correct because if the date is changed (either manually or automatically) the names are not updated.

We want to build a mechanism that will watch date changes and update the names accordingly.

Thanks!

**Comment by nater1983** [comment]
To use the date and time of the computer on which the script is running, you can directly assign the current system date and time to the currentDateTime variable. You can achieve this by using the Date object in JavaScript. Replace the line:

`currentDateTime = GLib.DateTime.new_now_local();
`
with
` currentDateTime = new Date();
`

**Comment by nater1983** [comment]
that mite work
